### ISSUE TITLE
Diagramma casi d'uso

### ISSUE THREAD

**Issue by AlessandroBiscaro** [AlessandroBiscaro/SportMate#14]

**Comment by Thomas-Fabbris** [comment]
Ho notato che il diagramma dei casi d'uso e la specifica dei requisiti sono in disaccordo (manca modifica dei dati gestore/utente nell'elenco funzionalità)

**Comment by AlessandroBiscaro** [comment]
Risolto, sistemato diagramma e Specifica dei Requisiti
